project_name: gopass-json
version: 2

before:
  hooks:
    - go mod download

builds:
  - id: gopass-json
    binary: gopass-json
    main: ./cmd/gopass-json
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: gopass-json
    name_template: "{{.Binary}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE
      - docs/api.md

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_SHA256SUMS"

release:
  github:
    owner: 3dyuval
    name: gopass-json
  draft: false
  prerelease: auto
